config/routes.rb
Rails.application.routes.draw do

  namespace :action_cost do
    get '/' => 'dashboards#index'
    match '/ca/:ca' => 'dashboards#ca', :as => 'ca', :constraints => { :ca => /.*/ }
    #resources :dashboards
  end

end

app/controllers/action_cost/dashboards_controller.rb
class ActionCost::DashboardsController < ApplicationController

  layout 'action_cost'
  
  def index
    respond_to do |format|
      format.json do
        render :json => ActionCost::Middleware.accumulated_stats.to_json
      end
      format.html do
        @data = ActionCost::Middleware.accumulated_stats
        ca_sums = {}
        @data.each_pair do |key, val|
          #val[:operations]['select'] = 0 unless val[:operations]['select']
          ca_sums[key] = val[:operations][:rc]['select'] + val[:operations][:sql]['select']
        end
        @sorted_cas = ca_sums.sort_by { |k,v| v/@data[k][:num] }.reverse.map { |v| v[0] }
        render
      end
    end
  end


  def ca
    ca = params[:ca]
    @data = ActionCost::Middleware.accumulated_stats
    @num = @data[ca][:num]
    @tables = @data[ca][:tables]
    @rc_sorted_table_names  = @tables[:rc].sort_by { |k,v| v/@data[ca][:num] }.reverse.map { |v| v[0] }
    @sql_sorted_table_names = @tables[:sql].sort_by { |k,v| v/@data[ca][:num] }.reverse.map { |v| v[0] }
  end
end

app/views/action_cost/dashboards/ca.html.erb
<h1>RecordCache queries</h1>
<table width=400px">
  <tr>
    <th width=200px>Table</th>
    <th width=200px>Query count</th>
  </tr>
  <% @rc_sorted_table_names.each do |table| %>
    <tr>
      <td><%= table %></td>
      <td><%= @tables[:rc][table]/@num %></td>
    </tr>
  <% end %>
</table>
<br/>

<h1>SQL queries</h1>
<table width="400px">
  <tr>
    <th width=200px>Table</th>
    <th width=200px>Query count</th>
  </tr>
  <% @sql_sorted_table_names.each do |table| %>
    <tr>
      <td><%= table %></td>
      <td><%= @tables[:sql][table]/@num %></td>
    </tr>
  <% end %>
</table>

<br/>
<%= link_to 'All controller actions', action_cost_path %>

app/views/action_cost/dashboards/index.html.erb
<table width="100%">
  <tr>
    <th>Controller Action</th>
    <th>RecordCache Select</th>
    <th>SQL Select</th>
    <th>SQL Update</th>
    <th>SQL Insert</th>
    <th>SQL Delete</th>
    <th>Calls</th>
  </tr>
  <% @sorted_cas.each do |ca| %>
  <% num = @data[ca][:num] %>
    <tr>
      <td><%= link_to ca, action_cost_ca_path(URI::escape(ca)) %></td>
      <td><%= @data[ca][:operations][:rc]['select'] / num %></td>
      <td><%= @data[ca][:operations][:sql]['select'] / num %></td>
      <td><%= @data[ca][:operations][:sql]['update'] / num %></td>
      <td><%= @data[ca][:operations][:sql]['insert'] / num %></td>
      <td><%= @data[ca][:operations][:sql]['delete'] / num %></td>
      <td><%= num %></td>
    </tr>
  <% end %>
</table>

<br/>

app/views/layouts/action_cost.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActionCost Dashboard</title>
  <%= csrf_meta_tag %>

  <style>
    body, td, th {
        font-family: Verdana, Arial, sans-serif;
        font-size: 14px }
    th {
      text-align: right;
      font: bold
    }
    tr { border-top: 1px solid #444;
         text-align: right
       }
    td { text-align: right }
  </style>
</head>
<body>

<%= yield %>

<br>
<p><%= link_to 'Back to the application', '/' %></p>

</body>
</html>